name: DeepDSI
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.8.0
  - pip=24.3.1
  - pyg=2.5.2
  - cudatoolkit=11.3.1
  - pytorch=1.12.1
  - h5py=3.11.0
  - matplotlib=3.5.0
  - numpy=1.23.2
  - pandas=1.3.4
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - seaborn=0.11.2
  - learn2learn=0.2.0
  - tqdm=4.62.3
  - pip:
      - learn2learn=0.2.0
      - numpy=1.23.2
