name: MetaESI
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.8.0
  - pip=24.3.1
  - pyg=2.5.2
  - cudatoolkit=11.3.1
  - pytorch=1.12.1
  - h5py=3.11.0
  - biopython=1.78
  - pandas=1.5.3
  - tqdm=4.62.3
  - pip:
      - learn2learn==0.2.0
      - numpy==1.23.2
      - opencv-python==4.10.0.84
